ALTER SESSION SET "_ORACLE_SCRIPT" = true;
DROP USER RENTA_CAR CASCADE;
DROP ROLE DIRECTOR;
DROP ROLE GERENTE;
DROP ROLE RECEPCIONISTA;
DROP ROLE CONDUCTOR;
DROP ROLE LAVADOR;
DROP ROLE ENCARGADO_LIMPIEZA;
