ALTER SESSION SET "_ORACLE_SCRIPT" = true;  

DROP USER ADMINISTRADOR CASCADE;
DROP USER jmedina;
DROP USER manueljr;
DROP USER pfernan;
DROP USER amontero;
DROP USER user_mecanico;

DROP ROLE DIRECTOR;
DROP ROLE GERENTE;
DROP ROLE RECEPCIONISTA;
DROP ROLE CONDUCTOR;
DROP ROLE MECANICO;
